### ISSUE TITLE
Integration with One Page Checkout PS

### ISSUE THREAD

**Issue by jbustamanterendon** [firstred/mdstripe#49]
Hello,

We have seen that you have provided for integration with our module for prestashop "One Page Checkout PS", but does not work correctly.

We are attaching "eupayment.tpl" modified to work properly with our module.

Any questions, please contact us, thank you.

Best regards.

[mdstripe_mod.zip](https://github.com/firstred/mdstripe/files/553708/mdstripe_mod.zip)

**Comment by firstred** [comment]
Your module is no longer supported. 
You can just pick the data from the `displayPaymentEU` hook instead and redirect the user to the URL it returns.

**Comment by jbustamanterendon** [comment]
Question: Why say this on lines 1224 - mdstripe.php ?

`if (Module::isEnabled('onepagecheckoutps')) {
   return $this->display(__FILE__, 'views/templates/front/eupayment.tpl');
`}

Thanks.

**Comment by firstred** [comment]
Because it was supported in the past, but I discovered that none of the one page checkout modules can use the API properly, which I fully understand, because PrestaShop doesn't provide a correct one.

Therefore, since your checkout is EU-like, I'd like to recommend to use the `displayPaymentEU` hook, so that the module can extract `cta_text`, `logo`, `action` instead and keep working with every update.

**Comment by jbustamanterendon** [comment]
Please, remove lines: 1224, 1225 & 1226:
        if (Module::isEnabled('onepagecheckoutps')) {
            return $this->display(__FILE__, 'views/templates/front/eupayment.tpl');
        }

Thanks.
