### ISSUE TITLE
Missing /vendor/autoload.php

### ISSUE THREAD

**Issue by kjackson23** [firstred/mdstripe#69]
Probably just a newb mistake on my part, but I attempted to install the zip via the back office and received the following error:

Fatal error: require_once() [function.require.html]: Failed opening required 'W:\xampp713\htdocs\prestashop\modules\mdstripe/vendor/autoload.php' (include_path='W:\xampp713\htdocs\prestashop\tools\htmlpurifier/standalone;W:\xampp713\php\PEAR') in W:\xampp713\htdocs\prestashop\modules\mdstripe\mdstripe.php **on line 24**

`Line 24: require_once dirname(__FILE__).'/vendor/autoload.php';`

Now my back office modules page is not working (just shows the error above).  There does not appear to be a vendor folder in the mdstripe folder, nor the autoload.php file. 

PS1.6.11, PHP 7.09 on Windows 8.1 XAMPP

**Comment by firstred** [comment]
Ha! You are obviously installing directly fron GitHub. Way too obvious :)

I recommend you to check out the releases tab where you will find a package
which you can upload directly.

On Feb 4, 2017 1:35 AM, "kjackson23" <notifications@github.com> wrote:

Probably just a newb mistake on my part, but I attempted to install the zip
via the back office and received the following error:

Fatal error: require_once() [function.require.html]: Failed opening
required 'W:\xampp713\htdocs\prestashop\modules\mdstripe/vendor/autoload.php'
(include_path='W:\xampp713\htdocs\prestashop\tools\
htmlpurifier/standalone;W:\xampp713\php\PEAR') in
W:\xampp713\htdocs\prestashop\modules\mdstripe\mdstripe.php *on line 24*

*Line 24: require_once dirname(FILE).'/vendor/autoload.php';*

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/firstred/mdstripe/issues/69>, or mute the thread

**Comment by kjackson23** [comment]
Indeed.  Ha! Thank you.
